name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish_image:
    name: Build and push naka image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Remove 'v' from tag
        env:
          github_ref: ${{ github.ref }}
        run: |
          github_ref=${github_ref##*/}
          github_ref=${github_ref/v/}
          echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: |
            rl404/naka:latest
            rl404/naka:${{ env.IMG_TAG }}
            ghcr.io/rl404/naka:latest
            ghcr.io/rl404/naka:${{ env.IMG_TAG }}

      - name: Auth gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Setup GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          location: ${{ secrets.GKE_LOCATION }}
      - name: Deploy
        run: |
          kubectl set image deployment ${{ secrets.GKE_DEPLOYMENT_NAME }} ${{ secrets.GKE_CONTAINER_NAME }}=rl404/naka:${{ env.IMG_TAG }}
